name: eezy_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_form_builder: ^9.2.1
  flutter_smart_dialog: ^4.9.6
  get: ^4.6.6
  getwidget: ^4.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  http: ^1.2.1
  iconsax: ^0.0.8
  image_picker: ^1.0.4
  image_picker_web: ^3.1.1
  m_toast: ^0.2.4
  mime_type: ^1.0.0
  pocketbase: ^0.18.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/jsons/
